"""Declarative base, naming conventions, and the column shapes every table shares.

Two rules here are load-bearing rather than stylistic.

The ``ck`` naming convention interpolates ``%(constraint_name)s``, so a ``CheckConstraint``
created without an explicit name raises ``InvalidRequestError`` when DDL is emitted. Always
pass a name; ``named_check`` exists so that is hard to forget.

PostgreSQL truncates identifiers at 63 bytes, and it truncates silently, so two different
constraints on a wide table can collapse into one name. ``over_length_identifiers`` reports
them so a test fails instead.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import BigInteger, CheckConstraint, DateTime, MetaData, func, text
from sqlalchemy.dialects.postgresql import UUID as PostgresUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

MAX_IDENTIFIER_BYTES = 63


class Base(DeclarativeBase):
    """Base for module-owned ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def named_check(expression: str, *, name: str) -> CheckConstraint:
    """Build a CheckConstraint carrying the explicit name the convention requires."""

    if not name:
        raise ValueError("check constraints must be named; the ck convention interpolates the name")
    return CheckConstraint(expression, name=name)


def uuid_primary_key() -> Mapped[uuid.UUID]:
    """Primary key generated by the database, so an insert never depends on the caller."""

    return mapped_column(
        PostgresUUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at_column() -> Mapped[datetime]:
    """Creation instant, always stored with a timezone.

    TIMESTAMPTZ plus a ``now()`` server default means a naive datetime cannot be persisted,
    matching ``app.core.time.ensure_utc``, which rejects one in application code.
    """

    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


def updated_at_column() -> Mapped[datetime]:
    """Last-modified instant for a mutable aggregate.

    Maintained by the application inside the same transaction as the change, never by a
    trigger, so the value belongs to the reviewed unit of work rather than to a side effect.
    """

    return mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


def record_version_column() -> Mapped[int]:
    """Optimistic-concurrency counter, for a **mutable aggregate only**.

    Never put this on an append-only or immutable-snapshot table. A row that cannot change
    has nothing to version, and a version column there invites a compare-and-swap that
    appears to succeed against a record nobody may modify.
    """

    return mapped_column(BigInteger, nullable=False, server_default=text("1"))


def over_length_identifiers(metadata: MetaData | None = None) -> list[str]:
    """Return every identifier PostgreSQL would silently truncate at 63 bytes."""

    target = Base.metadata if metadata is None else metadata
    too_long: list[str] = []
    for table in target.tables.values():
        names: list[str | None] = [table.name]
        names.extend(constraint.name for constraint in table.constraints)  # type: ignore[misc]
        names.extend(index.name for index in table.indexes)
        names.extend(column.name for column in table.columns)
        for candidate in names:
            if candidate is None:
                continue
            encoded = str(candidate).encode("utf-8")
            if len(encoded) > MAX_IDENTIFIER_BYTES:
                too_long.append(f"{table.name}: {candidate} ({len(encoded)} bytes)")
    return sorted(too_long)
