"""Storage keys: generated by the server, opaque, and never derived from input.

`storage_key` is not a client contract. A caller uploads a file and names it; the
server decides where the bytes live and hands back an identifier the caller never
sees. Three properties follow, and each closes a specific hole:

**Nothing from the client reaches the path.** Not the filename, not the extension,
not a caller-supplied identifier. A filename in a path is a traversal surface
(`../../etc/passwd`), a collision surface (two traders uploading `receipt.pdf`),
and an information leak (the filename becomes visible to anyone who can list a
bucket). Sanitising the filename would address the first and leave the other two.

**No extension either.** It would be the one client-derived fragment left, and it
buys nothing: the MIME type lives in `file_objects.mime_type_declared` and
`mime_type_detected`, which is where a reader should look anyway. A key ending
`.php` or `.svg` is only ever a liability.

**The random component is 128 bits from `secrets`, not `uuid4()` cosmetics.** Keys
must be unguessable even when one is known, because knowing the layout is how an
enumeration attack starts. `secrets.token_hex` is the module that promises this;
`random` does not, and `uuid4` only does by implementation detail.

Date partitioning is for operators rather than for lookup — nothing resolves a file
by walking the tree — so it can be coarse. Day granularity keeps a directory
listing usable during an incident without encoding anything about the file.
"""

from __future__ import annotations

import re
import secrets
from datetime import datetime

from app.core.time import ensure_utc

# Lower-case, digits, underscore. A category reaches the key, so it is constrained
# rather than trusted: categories come from our own code today, and the point of a
# guard is the caller who does not exist yet.
_CATEGORY = re.compile(r"^[a-z][a-z0-9_]{0,39}$")

# 16 bytes rendered as 32 hex characters.
_RANDOM_BYTES = 16


class InvalidStorageCategoryError(ValueError):
    """The category is not usable as a path segment."""


def generate_storage_key(*, category: str, moment: datetime) -> str:
    """Build an opaque key: `<category>/<YYYY>/<MM>/<DD>/<32 hex>`.

    `moment` is passed in rather than read from the clock, so a caller inside a
    command transaction uses the same instant it records elsewhere and a test does
    not have to freeze time. Requiring it also means this function has no hidden
    dependency on the current time, which is what makes it deterministic.
    """

    if not _CATEGORY.match(category):
        raise InvalidStorageCategoryError(
            f"category must match {_CATEGORY.pattern} to be safe as a path "
            f"segment; got {category!r}. Categories come from our own code, so "
            "this failing means a caller is passing something it should not."
        )
    # `ensure_utc` refuses a naive datetime rather than assuming a zone, so keys
    # cannot be partitioned by whatever local clock the host happens to have. It
    # also converts, so a Tehran-time caller and a UTC one agree on the folder —
    # which matters because the partition is what an operator scans during an
    # incident.
    utc = ensure_utc(moment)
    return f"{category}/{utc.strftime('%Y/%m/%d')}/{secrets.token_hex(_RANDOM_BYTES)}"
