"""The approved permission identifiers, inlined for the runtime image.

Generated from `docs/governance/permission_catalog.yaml` by
`scripts/rbac_catalogue.py` and written here for the same reason migration
`20260801_0008` inlines the seed data: **`docs/` is not copied into the container
image**, so a module that read the catalogue at import would crash every
deployment on start-up. That is not hypothetical — the first version of
`app/security/permissions.py` did exactly this, and the failure would have been a
container that never became ready rather than a test that went red.

`tests/backend/test_permission_catalogue_inline.py` compares this list against
the catalogue, so a governance change that does not reach this file fails CI
rather than leaving a permission that exists in one place and not the other.

Only canonical identifiers appear. Document 05's spellings are deprecated aliases
under DOC-CONFLICT-013 and are deliberately absent: declaring an alias on a route
would make the grant depend on a mapping that never broadens authority and fails
closed when ambiguous.
"""

from __future__ import annotations

APPROVED_PERMISSIONS: frozenset[str] = frozenset(
    {
        "ai_configuration.read",
        "ai_configuration.update",
        "audit.export",
        "audit.read",
        "auth.session.read_all",
        "auth.session.read_own",
        "auth.session.revoke_all",
        "auth.session.revoke_own",
        "backup_status.read",
        "bank_export.download",
        "bank_export.generate_final",
        "bank_export.generate_preview",
        "bank_export.mark_sent",
        "bank_export.quarantine",
        "bank_export.read",
        "bank_mapping.activate",
        "bank_mapping.create_version",
        "bank_profile.activate_version",
        "bank_profile.create_version",
        "bank_profile.read",
        "bank_result_bundle.close",
        "bank_result_bundle.link_batch",
        "bank_result_bundle.read",
        "bank_result_bundle.upload",
        "bank_statement.import",
        "bank_statement.read",
        "bank_statement.upload",
        "beneficiary.create",
        "beneficiary.create_own",
        "beneficiary.deactivate",
        "beneficiary.read",
        "beneficiary.update_future",
        "break_glass.activate",
        "break_glass.review",
        "evidence_link.confirm",
        "evidence_link.replace",
        "evidence_link.revoke",
        "feature_flag.read",
        "feature_flag.update",
        "file.download",
        "file.download_bank_export",
        "file.preview",
        "file.quarantine_review",
        "file.read_metadata",
        "file.read_sensitive_bundle",
        "file.upload",
        "gold_sale.cancel",
        "gold_sale.create_own",
        "gold_sale.dispatch",
        "gold_sale.price",
        "gold_sale.read",
        "gold_sale.review",
        "incoming_payment.confirm",
        "incoming_payment.correct",
        "incoming_payment.match",
        "incoming_receipt.create_own",
        "incoming_receipt.read",
        "legal_hold.manage",
        "legal_hold.read",
        "manual_review.assign",
        "manual_review.read",
        "manual_review.resolve",
        "matching_candidate.create",
        "matching_candidate.review",
        "payment_attempt.confirm_failed",
        "payment_attempt.confirm_paid",
        "payment_attempt.correct_result",
        "payment_attempt.create_retry",
        "payment_attempt.read",
        "payment_batch.cancel_draft",
        "payment_batch.create",
        "payment_batch.read",
        "payment_batch_version.approve",
        "payment_batch_version.create",
        "payment_batch_version.finalize",
        "payment_batch_version.invalidate_approval",
        "payment_batch_version.read_approval_view",
        "payment_batch_version.reject",
        "payment_publication.acknowledge_own",
        "payment_publication.correct",
        "payment_publication.dispute_own",
        "payment_publication.preview",
        "payment_publication.publish",
        "payment_publication.read_own",
        "payment_request.cancel",
        "payment_request.create_internal",
        "payment_request.create_own",
        "payment_request.create_revision_internal",
        "payment_request.create_revision_own",
        "payment_request.mark_eligible",
        "payment_request.read",
        "payment_request.read_own",
        "payment_request.request_correction",
        "payment_request.review",
        "payment_request.submit",
        "permission.read",
        "receipt_segment.create_crop",
        "receipt_segment.create_external",
        "receipt_segment.read",
        "report.export",
        "report.read",
        "retention.activate",
        "retention.approve",
        "retention.propose",
        "retention.read",
        "role.manage",
        "role.read",
        "security_event.read",
        "source_bank_account.manage",
        "trader.approve",
        "trader.create",
        "trader.reactivate",
        "trader.read",
        "trader.reject",
        "trader.suspend",
        "trader.update_business",
        "user.create",
        "user.deactivate",
        "user.read",
        "user.update",
    }
)
