"""Add the file metadata foundation: objects, attachments and derivations.

Generated by `alembic revision --autogenerate` against a database at 20260801_0010,
then edited to add the grants and to fix the downgrade.

**The grants narrow for the first time in this schema.** Every earlier mutable
table received `GRANT UPDATE, DELETE` as a pair. Here `file_objects` and
`file_links` get **UPDATE only**, and `file_derivations` gets neither.

That is not caution for its own sake. A `file_objects` row is the record that a
file was uploaded, by whom, and what its bytes hashed to; a `file_links` row is the
record that it was attached to something. Both change state — pending becomes
available, a link is superseded — so both need UPDATE. Neither has any path that
should remove the record, because supersession is modelled as `replaced_at` and
deletion is modelled as `physically_deleted_at` plus a status, and ADR-005 is open
so the retention process that would set either does not exist. Granting DELETE
"because the table is mutable" would hand the runtime the one verb that makes the
evidence of an upload disappear, for no caller that needs it.

`file_derivations` receives nothing beyond the fail-closed default of SELECT and
INSERT. A derivation records what a job produced from which inputs; `source_hash`
and `renderer_version` are facts as of the moment it ran. Re-deriving is a new row,
and the reproducibility unique is what stops two contradictory answers existing for
the same question — an UPDATE would let one be rewritten into the other.

**Two conditional constraints are the substance of this revision**, and both exist
because doc 04 states a rule in prose and supplies no constraint:

`ck_file_objects_available_requires_hash` — a file cannot be `available` with a
null checksum. Without it the rule lives in application code, and the first path
that forgets produces evidence with nothing to verify it against.

`ck_file_objects_available_requires_clean_scan` — a file cannot be `available`
unless its scan came back clean. Written as a whitelist of the single permitted
scan value rather than a blacklist of the refused ones, so a scan outcome nobody
has enumerated fails closed. This is what lets the revision ship **no**
`scan_status` value CHECK at all while still honouring ADR-008's safe default:
DOC-CONFLICT-029 and ADR-008 are both Open, and enumerating the outcomes from a
migration would decide them.

**`storage_status` carries a seven-value CHECK**, which is the eight spellings
`status_catalog.yaml` records for `file_object` minus `deleted_by_policy`. The
catalogue sets `canonical: null` and forbids canonicalising `deleted` against
`deleted_by_policy`; this does not canonicalise them. It keeps `deleted` and
declines to permit the value whose only writer would be a policy-driven deletion,
which ADR-005 blocks from existing. Permitting it later is a visible widening
migration, together with the `physically_deleted_at` constraint that names the same
state — the right amount of friction for the status that means "a policy erased
this".

Downgrade drops the three tables. Honest only while they are empty: a file
metadata row is the record of an upload, so this shares the limit stated in
20260801_0004 and is the reason the policy is forward-fix.

Revision ID: 20260801_0011
Revises: 20260801_0010
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260801_0011"
down_revision: str | Sequence[str] | None = "20260801_0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# UPDATE without DELETE. Both tables transition through states; neither has a
# caller that should make the record go away.
UPDATE_ONLY_TABLES: tuple[str, ...] = ("file_objects", "file_links")

# Named here so the omission is a statement rather than an oversight:
# `file_derivations` receives nothing beyond SELECT and INSERT.
APPEND_ONLY_TABLES: tuple[str, ...] = ("file_derivations",)


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE (or APP_DB_USER)": settings.app_db_role,
        "WORKER_DB_ROLE (or WORKER_DB_USER)": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(value for value in configured.values() if value)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_objects",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("storage_provider", sa.String(length=40), nullable=False),
        sa.Column("storage_bucket", sa.String(length=120), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("mime_type_declared", sa.String(length=160), nullable=False),
        sa.Column("mime_type_detected", sa.String(length=160), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256_hash", sa.String(length=64), nullable=True),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("visibility_scope", sa.String(length=60), nullable=False),
        sa.Column("retention_class", sa.String(length=80), nullable=True),
        sa.Column("legal_hold_state", sa.String(length=40), nullable=True),
        sa.Column("storage_status", sa.String(length=32), nullable=False),
        sa.Column("scan_status", sa.String(length=48), nullable=False),
        sa.Column("uploaded_by_actor_type", sa.String(length=32), nullable=False),
        sa.Column("uploaded_by_actor_id", sa.UUID(), nullable=True),
        sa.Column("retention_policy_id", sa.UUID(), nullable=True),
        sa.Column("original_or_derived_relation", sa.String(length=16), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("physically_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "original_or_derived_relation IN ('original', 'derived')",
            name=op.f("ck_file_objects_original_or_derived_relation"),
        ),
        sa.CheckConstraint(
            "physically_deleted_at IS NULL OR storage_status = 'deleted'",
            name=op.f("ck_file_objects_physical_deletion_implies_deleted_status"),
        ),
        sa.CheckConstraint(
            "sha256_hash IS NULL OR sha256_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_file_objects_sha256_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "storage_status <> 'available' OR scan_status = 'clean'",
            name=op.f("ck_file_objects_available_requires_clean_scan"),
        ),
        sa.CheckConstraint(
            "storage_status <> 'available' OR sha256_hash IS NOT NULL",
            name=op.f("ck_file_objects_available_requires_hash"),
        ),
        sa.CheckConstraint(
            "storage_status IN ('pending', 'quarantined', 'available', 'processing_failed', "
            "'archived', 'retention_pending', 'deleted')",
            name=op.f("ck_file_objects_storage_status"),
        ),
        sa.CheckConstraint(
            "uploaded_by_actor_type IN ('trader_user', 'admin_user', 'system_worker', "
            "'system_maintenance')",
            name=op.f("ck_file_objects_actor_type"),
        ),
        sa.CheckConstraint(
            "length(btrim(original_filename)) > 0",
            name=op.f("ck_file_objects_original_filename_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(storage_key)) > 0", name=op.f("ck_file_objects_storage_key_not_blank")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_file_objects_size_is_not_negative")),
        sa.ForeignKeyConstraint(
            ["retention_policy_id"],
            ["retention_policies.id"],
            name=op.f("fk_file_objects_retention_policy_id_retention_policies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_objects")),
        sa.UniqueConstraint(
            "storage_provider",
            "storage_bucket",
            "storage_key",
            name="uq_file_objects_storage_location",
        ),
    )
    op.create_index("idx_file_objects_hash", "file_objects", ["sha256_hash"], unique=False)
    op.create_index(
        "idx_file_objects_status_category",
        "file_objects",
        ["storage_status", "category"],
        unique=False,
    )
    op.create_table(
        "file_derivations",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("source_file_id", sa.UUID(), nullable=False),
        sa.Column("derived_file_id", sa.UUID(), nullable=False),
        sa.Column("derivation_type", sa.String(length=60), nullable=False),
        sa.Column("parameters_hash", sa.String(length=80), nullable=False),
        sa.Column("renderer_version", sa.String(length=60), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_job_id", sa.UUID(), nullable=True),
        sa.Column(
            "parameters",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "parameters_hash ~ '^v[0-9]+:[0-9a-f]{64}$'",
            name=op.f("ck_file_derivations_parameters_hash_is_a_versioned_digest"),
        ),
        sa.CheckConstraint(
            "source_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_file_derivations_source_hash_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "length(btrim(derivation_type)) > 0",
            name=op.f("ck_file_derivations_derivation_type_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(renderer_version)) > 0",
            name=op.f("ck_file_derivations_renderer_version_not_blank"),
        ),
        sa.CheckConstraint(
            "source_file_id <> derived_file_id",
            name=op.f("ck_file_derivations_derivation_is_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_job_id"],
            ["processing_jobs.id"],
            name=op.f("fk_file_derivations_created_by_job_id_processing_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["derived_file_id"],
            ["file_objects.id"],
            name=op.f("fk_file_derivations_derived_file_id_file_objects"),
        ),
        sa.ForeignKeyConstraint(
            ["source_file_id"],
            ["file_objects.id"],
            name=op.f("fk_file_derivations_source_file_id_file_objects"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_derivations")),
        sa.UniqueConstraint(
            "source_file_id",
            "derivation_type",
            "parameters_hash",
            "renderer_version",
            name="uq_file_derivations_reproducibility",
        ),
        sa.UniqueConstraint(
            "source_file_id", "derived_file_id", name="uq_file_derivations_source_derived"
        ),
    )
    op.create_index(
        "idx_file_derivations_derived", "file_derivations", ["derived_file_id"], unique=False
    )
    op.create_index(
        "idx_file_derivations_source",
        "file_derivations",
        ["source_file_id", "derivation_type"],
        unique=False,
    )
    op.create_table(
        "file_links",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("link_role", sa.String(length=80), nullable=False),
        sa.Column("attached_by_actor_type", sa.String(length=32), nullable=False),
        sa.Column("attached_by_actor_id", sa.UUID(), nullable=True),
        sa.Column("replaced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_file_link_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "attached_by_actor_type IN ('trader_user', 'admin_user', 'system_worker', "
            "'system_maintenance')",
            name=op.f("ck_file_links_actor_type"),
        ),
        sa.CheckConstraint(
            "(replaced_at IS NULL AND replaced_by_file_link_id IS NULL) "
            "OR (replaced_at IS NOT NULL AND replaced_by_file_link_id IS NOT NULL)",
            name=op.f("ck_file_links_replacement_fields_move_together"),
        ),
        sa.CheckConstraint(
            "length(btrim(resource_type)) > 0", name=op.f("ck_file_links_resource_type_not_blank")
        ),
        sa.CheckConstraint(
            "replaced_by_file_link_id IS NULL OR replaced_by_file_link_id <> id",
            name=op.f("ck_file_links_replacement_is_not_self"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["file_objects.id"], name=op.f("fk_file_links_file_id_file_objects")
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by_file_link_id"],
            ["file_links.id"],
            name=op.f("fk_file_links_replaced_by_file_link_id_file_links"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_file_links")),
    )
    op.create_index(
        "idx_file_links_active",
        "file_links",
        ["resource_type", "resource_id", "link_role"],
        unique=False,
        postgresql_where=sa.text("replaced_at IS NULL"),
    )
    op.create_index("idx_file_links_file", "file_links", ["file_id"], unique=False)
    # ### end Alembic commands ###

    # UPDATE only. DELETE is withheld from all three tables: supersession is a
    # column, deletion is a status plus a timestamp, and the process that would
    # set the latter is blocked by an open ADR. `file_derivations` appears in
    # neither loop and keeps only the fail-closed default of SELECT and INSERT.
    bind = op.get_bind()
    for role in _runtime_roles():
        for table in UPDATE_ONLY_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE ON public."{table}" TO "{role}"'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_file_links_file", table_name="file_links")
    op.drop_index(
        "idx_file_links_active",
        table_name="file_links",
        postgresql_where=sa.text("replaced_at IS NULL"),
    )
    op.drop_table("file_links")
    op.drop_index("idx_file_derivations_source", table_name="file_derivations")
    op.drop_index("idx_file_derivations_derived", table_name="file_derivations")
    op.drop_table("file_derivations")
    op.drop_index("idx_file_objects_status_category", table_name="file_objects")
    op.drop_index("idx_file_objects_hash", table_name="file_objects")
    op.drop_table("file_objects")
    # ### end Alembic commands ###
