"""Add the configuration surface and the inert retention/legal-hold structures.

Generated by `alembic revision --autogenerate` against a database at 20260801_0009,
then edited to add the grants, to seed the five Phase 1A feature flags, and to fix
the downgrade.

**All four tables are mutable, and all four receive UPDATE and DELETE.** That is
the opposite of the treatment `audit_logs` and `auth_events` get, and it is
correct: a setting is changed, a flag is toggled, a retention policy is approved
then activated, a legal hold is released. None of these is a record of something
that happened — they are current state, and current state that cannot be corrected
is worse than one that can. What makes the change accountable is the audit row the
write path writes beside it, not an inability to write.

**The five seeded flags are exactly the five from `04:1502-1506`.** Seeded here
rather than by a bootstrap script so that a fresh database and a migrated one are
the same database, and so the values are reviewable in a diff. `ON CONFLICT DO
NOTHING`, because the migrate container runs on every stack start: a second run
must neither fail nor overwrite a value an operator has since changed. That last
part is the reason this seed does not upsert — an operator turning `manual_crop`
off would find it back on after the next deploy, and a configuration that silently
reverts is a configuration nobody can trust.

**`break_glass_enabled` is seeded in no value at all**, and the CHECK constraint on
`flag_key` rejects any key containing `break_glass` regardless of who writes it.
POL-005 is Approved and disables break-glass activation, permission grants,
endpoints, *feature flags* and runtime bypasses — the flag itself, not merely its
enablement. Enforcing it in the database rather than by omission matters because
`feature_flag.update` is granted by default to `technical_admin`, the one role
that must hold no financial authority: without the constraint, that role could
create the bypass at runtime and nothing would have said no.

**Nothing here deletes anything.** `retention_policies` and `legal_holds` are
structure. There is no executor, no purge job, no expiry sweeper and no trigger in
this revision or anywhere else, and `tests/integration/test_configuration_and_retention.py`
asserts that structurally rather than by inspection. ADR-005 is open; the governed
procedures that would authorise a deletion do not exist yet, and a table that can
express a retention policy is useful for review long before anything may act on
one.

Downgrade drops the four tables. Honest here in a way it is not for the
append-only tables: none of these holds recorded evidence, and dropping them loses
current configuration, which a redeploy restores.

Revision ID: 20260801_0010
Revises: 20260801_0009
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260801_0010"
down_revision: str | Sequence[str] | None = "20260801_0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table in this revision holds current state rather than a record of an
# event, so every one of them is mutable. Contrast 20260801_0009, where the list
# deliberately excluded `auth_events`.
MUTABLE_TABLES: tuple[str, ...] = (
    "system_settings",
    "feature_flags",
    "retention_policies",
    "legal_holds",
)

# Exactly the five rows from 04:1502-1506. Kept in sync with
# `app.db.models.configuration.PHASE_1A_FLAGS` by
# tests/backend/test_seeded_flags_match_the_model.py, so the two cannot drift.
PHASE_1A_FLAGS: tuple[tuple[str, bool], ...] = (
    ("manual_crop.enabled", True),
    ("auto_segmentation.enabled", False),
    ("ocr.enabled", False),
    ("ai_matching.enabled", False),
    ("bank_api.enabled", False),
)


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE (or APP_DB_USER)": settings.app_db_role,
        "WORKER_DB_ROLE (or WORKER_DB_USER)": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(value for value in configured.values() if value)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("flag_key", sa.String(length=120), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "rollout_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "flag_key NOT LIKE '%%break_glass%%'",
            name=op.f("ck_feature_flags_break_glass_flag_is_prohibited"),
        ),
        sa.CheckConstraint(
            "flag_key = lower(flag_key)", name=op.f("ck_feature_flags_flag_key_is_lowercase")
        ),
        sa.CheckConstraint(
            "length(btrim(flag_key)) > 0", name=op.f("ck_feature_flags_flag_key_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_feature_flags_updated_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("flag_key", name=op.f("uq_feature_flags_flag_key")),
    )
    op.create_table(
        "legal_holds",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("placed_by_admin_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "placed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("released_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("released_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("release_reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(released_at IS NULL AND released_by_admin_user_id IS NULL "
            "AND release_reason IS NULL) "
            "OR (released_at IS NOT NULL AND released_by_admin_user_id IS NOT NULL "
            "AND release_reason IS NOT NULL)",
            name=op.f("ck_legal_holds_release_fields_move_together"),
        ),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0", name=op.f("ck_legal_holds_reason_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["placed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_legal_holds_placed_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["released_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_legal_holds_released_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_legal_holds")),
    )
    op.create_index(
        "idx_legal_holds_active",
        "legal_holds",
        ["resource_type", "resource_id"],
        unique=False,
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.create_table(
        "retention_policies",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("retention_class", sa.String(length=80), nullable=False),
        sa.Column("retention_seconds", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("supersedes_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("proposed_by_admin_user_id", sa.UUID(), nullable=False),
        sa.Column(
            "proposed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(activated_at IS NULL AND activated_by_admin_user_id IS NULL) "
            "OR (activated_at IS NOT NULL AND activated_by_admin_user_id IS NOT NULL)",
            name=op.f("ck_retention_policies_activation_fields_move_together"),
        ),
        sa.CheckConstraint(
            "(approved_at IS NULL AND approved_by_admin_user_id IS NULL) "
            "OR (approved_at IS NOT NULL AND approved_by_admin_user_id IS NOT NULL)",
            name=op.f("ck_retention_policies_approval_fields_move_together"),
        ),
        sa.CheckConstraint(
            "activated_at IS NULL OR approved_at IS NOT NULL",
            name=op.f("ck_retention_policies_activation_requires_approval"),
        ),
        sa.CheckConstraint(
            "retention_seconds > 0", name=op.f("ck_retention_policies_retention_is_positive")
        ),
        sa.CheckConstraint(
            "supersedes_id IS NULL OR supersedes_id <> id",
            name=op.f("ck_retention_policies_supersedes_is_not_self"),
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_retention_policies_version_positive")),
        sa.ForeignKeyConstraint(
            ["activated_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_retention_policies_activated_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_retention_policies_approved_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_retention_policies_proposed_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["retention_policies.id"],
            name=op.f("fk_retention_policies_supersedes_id_retention_policies"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_retention_policies")),
    )
    op.create_index(
        "idx_retention_policies_resource",
        "retention_policies",
        ["resource_type", "retention_class"],
        unique=False,
    )
    op.create_table(
        "system_settings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("value_type", sa.String(length=24), nullable=False),
        sa.Column("category", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("updated_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key NOT LIKE '%%password%%' AND key NOT LIKE '%%secret%%' "
            "AND key NOT LIKE '%%token%%' AND key NOT LIKE '%%credential%%' "
            "AND key NOT LIKE '%%private_key%%' AND key NOT LIKE '%%api_key%%' "
            "AND key NOT LIKE '%%access_key%%' AND key NOT LIKE '%%encryption_key%%'",
            name=op.f("ck_system_settings_key_is_not_a_secret"),
        ),
        sa.CheckConstraint(
            "value_type IN ('string', 'integer', 'boolean', 'json', 'duration_seconds')",
            name=op.f("ck_system_settings_value_type"),
        ),
        sa.CheckConstraint("key = lower(key)", name=op.f("ck_system_settings_key_is_lowercase")),
        sa.CheckConstraint("length(btrim(key)) > 0", name=op.f("ck_system_settings_key_not_blank")),
        sa.ForeignKeyConstraint(
            ["updated_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_system_settings_updated_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_system_settings_key")),
    )
    op.create_index("idx_system_settings_category", "system_settings", ["category"], unique=False)
    # ### end Alembic commands ###

    bind = op.get_bind()

    # Every table here is current state rather than an event record, so every one
    # is mutable. `updated_by_admin_user_id` plus the audit row the write path
    # emits is what makes a change accountable — not an inability to write.
    for role in _runtime_roles():
        for table in MUTABLE_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE, DELETE ON public."{table}" TO "{role}"'))

    # DO NOTHING rather than an upsert: the migrate container runs on every stack
    # start, and re-asserting the seeded value would silently undo an operator's
    # deliberate change on the next deploy.
    for flag_key, is_enabled in PHASE_1A_FLAGS:
        bind.execute(
            sa.text(
                "INSERT INTO feature_flags (flag_key, is_enabled) "
                "VALUES (:flag_key, :is_enabled) "
                "ON CONFLICT (flag_key) DO NOTHING"
            ),
            {"flag_key": flag_key, "is_enabled": is_enabled},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_system_settings_category", table_name="system_settings")
    op.drop_table("system_settings")
    op.drop_index("idx_retention_policies_resource", table_name="retention_policies")
    op.drop_table("retention_policies")
    op.drop_index(
        "idx_legal_holds_active",
        table_name="legal_holds",
        postgresql_where=sa.text("released_at IS NULL"),
    )
    op.drop_table("legal_holds")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
