"""Add auth sessions, security events and recent-auth contexts.

Generated by `alembic revision --autogenerate` against a database at 20260801_0008,
then edited only to split the grants and to fix the downgrade.

**The grants are not uniform, and that is the point of editing them by hand.**
`auth_sessions` and `recent_auth_contexts` are mutable — a session is revoked, a
context is consumed — so the runtime roles need UPDATE on both. `auth_events`
gets INSERT and SELECT only, the same append-only treatment as `audit_logs`: a
record of a failed login that the failing process can erase is not a record.
Under the fail-closed default from 20260801_0005 an ungranted table is already
immutable, so `auth_events` needs no revoke — it simply never receives one.

This revision also attaches the foreign key slice 1 deliberately deferred.
`audit_logs.recent_auth_context_id` was declared without it because the
referenced table did not exist yet; expand/contract means rows written in between
keep whatever they recorded, and new ones are checked. There is no ON DELETE:
cascading would erase the evidence of which assurance authorised a change, which
is the reason the column exists.

Downgrade drops the three tables and detaches the foreign key. `auth_events` is
append-only and holds recorded evidence, so this is honest only while the table
is empty — the same limit stated in 20260801_0004, and the reason the policy is
forward-fix rather than reversible.

Revision ID: 20260801_0009
Revises: 20260801_0008
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260801_0009"
down_revision: str | Sequence[str] | None = "20260801_0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# A session is revoked; a recent-auth context is consumed. Both change after
# they are written, so both need UPDATE. `auth_events` does not appear here and
# that omission is the append-only guarantee.
MUTABLE_TABLES: tuple[str, ...] = ("auth_sessions", "recent_auth_contexts")


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE (or APP_DB_USER)": settings.app_db_role,
        "WORKER_DB_ROLE (or WORKER_DB_USER)": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(value for value in configured.values() if value)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_events",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("event_class", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("correlation_id", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("metadata_schema", sa.String(length=120), nullable=False),
        sa.Column("metadata_version", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('trader_user', 'admin_user', 'system_worker', 'system_maintenance')",
            name=op.f("ck_auth_events_actor_type"),
        ),
        sa.CheckConstraint(
            "event_class IN ('authentication', 'authorization', 'session', "
            "'credential', 'account_state', 'administrative')",
            name=op.f("ck_auth_events_event_class"),
        ),
        sa.CheckConstraint(
            "length(btrim(event_type)) > 0", name=op.f("ck_auth_events_event_type_not_blank")
        ),
        sa.CheckConstraint(
            "metadata_version > 0", name=op.f("ck_auth_events_metadata_version_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_events")),
    )
    op.create_index(
        "idx_auth_events_actor_time",
        "auth_events",
        ["actor_type", "actor_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "idx_auth_events_class_time", "auth_events", ["event_class", "created_at"], unique=False
    )
    op.create_index(
        "idx_auth_events_correlation_id", "auth_events", ["correlation_id"], unique=False
    )
    op.create_index(
        "idx_auth_events_failures",
        "auth_events",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("outcome <> 'success'"),
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=True),
        sa.Column("trader_user_id", sa.UUID(), nullable=True),
        sa.Column("secret_hash", sa.String(length=128), nullable=False),
        sa.Column("auth_level", sa.String(length=32), nullable=False),
        sa.Column(
            "authenticated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("step_up_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revocation_reason", sa.String(length=120), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column(
            "security_stamp_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("replaced_session_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "((admin_user_id IS NOT NULL)::int + (trader_user_id IS NOT NULL)::int) = 1",
            name=op.f("ck_auth_sessions_exactly_one_actor"),
        ),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revocation_reason IS NULL) "
            "OR (revoked_at IS NOT NULL AND revocation_reason IS NOT NULL)",
            name=op.f("ck_auth_sessions_revocation_fields_move_together"),
        ),
        sa.CheckConstraint(
            "expires_at > authenticated_at",
            name=op.f("ck_auth_sessions_expires_after_authentication"),
        ),
        sa.CheckConstraint(
            "replaced_session_id IS NULL OR replaced_session_id <> id",
            name=op.f("ck_auth_sessions_replacement_is_not_self"),
        ),
        sa.CheckConstraint(
            "security_stamp_version > 0",
            name=op.f("ck_auth_sessions_security_stamp_version_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_auth_sessions_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["replaced_session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_auth_sessions_replaced_session_id_auth_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["trader_user_id"],
            ["trader_users.id"],
            name=op.f("fk_auth_sessions_trader_user_id_trader_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_auth_sessions")),
        sa.UniqueConstraint("secret_hash", name=op.f("uq_auth_sessions_secret_hash")),
    )
    op.create_index(
        "idx_auth_sessions_active_admin",
        "auth_sessions",
        ["admin_user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL AND admin_user_id IS NOT NULL"),
    )
    op.create_index(
        "idx_auth_sessions_active_trader",
        "auth_sessions",
        ["trader_user_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL AND trader_user_id IS NOT NULL"),
    )
    op.create_table(
        "recent_auth_contexts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=False),
        sa.Column("purpose", sa.String(length=120), nullable=False),
        sa.Column("resource_type", sa.String(length=80), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("assurance_factor", sa.String(length=48), nullable=False),
        sa.Column("challenge_hash", sa.String(length=128), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("consumed_by_command", sa.String(length=120), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_type IN ('trader_user', 'admin_user', 'system_worker', 'system_maintenance')",
            name=op.f("ck_recent_auth_contexts_actor_type"),
        ),
        sa.CheckConstraint(
            "(consumed_at IS NULL AND consumed_by_command IS NULL) "
            "OR (consumed_at IS NOT NULL AND consumed_by_command IS NOT NULL)",
            name=op.f("ck_recent_auth_contexts_consumption_fields_move_together"),
        ),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_recent_auth_contexts_expires_after_issue")
        ),
        sa.CheckConstraint(
            "length(btrim(purpose)) > 0", name=op.f("ck_recent_auth_contexts_purpose_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["auth_sessions.id"],
            name=op.f("fk_recent_auth_contexts_session_id_auth_sessions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recent_auth_contexts")),
        sa.UniqueConstraint("challenge_hash", name=op.f("uq_recent_auth_contexts_challenge_hash")),
    )
    op.create_index(
        "idx_recent_auth_live",
        "recent_auth_contexts",
        ["actor_id", "purpose", "resource_id", "expires_at"],
        unique=False,
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_index("idx_recent_auth_session", "recent_auth_contexts", ["session_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_audit_logs_recent_auth_context_id_recent_auth_contexts"),
        "audit_logs",
        "recent_auth_contexts",
        ["recent_auth_context_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    # Split deliberately. `auth_events` is absent from the mutable list and
    # therefore stays immutable under the fail-closed default: a security record
    # the failing process can rewrite is not a record.
    bind = op.get_bind()
    for role in _runtime_roles():
        for table in MUTABLE_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE, DELETE ON public."{table}" TO "{role}"'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_audit_logs_recent_auth_context_id_recent_auth_contexts"),
        "audit_logs",
        type_="foreignkey",
    )
    op.drop_index("idx_recent_auth_session", table_name="recent_auth_contexts")
    op.drop_index(
        "idx_recent_auth_live",
        table_name="recent_auth_contexts",
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_table("recent_auth_contexts")
    op.drop_index(
        "idx_auth_sessions_active_trader",
        table_name="auth_sessions",
        postgresql_where=sa.text("revoked_at IS NULL AND trader_user_id IS NOT NULL"),
    )
    op.drop_index(
        "idx_auth_sessions_active_admin",
        table_name="auth_sessions",
        postgresql_where=sa.text("revoked_at IS NULL AND admin_user_id IS NOT NULL"),
    )
    op.drop_table("auth_sessions")
    op.drop_index(
        "idx_auth_events_failures",
        table_name="auth_events",
        postgresql_where=sa.text("outcome <> 'success'"),
    )
    op.drop_index("idx_auth_events_correlation_id", table_name="auth_events")
    op.drop_index("idx_auth_events_class_time", table_name="auth_events")
    op.drop_index("idx_auth_events_actor_time", table_name="auth_events")
    op.drop_table("auth_events")
    # ### end Alembic commands ###
