"""Add the trader business, hang trader logins off it, and fix two defects M2 left.

Hand-written rather than autogenerated, because two of the four changes are
corrections and autogenerate has no way to express "this index was always meant to
be keyed on a column that did not exist".

**`traders`, per `04_Database_Schema.md:452-476`.** The business, as distinct from
the humans who sign in for it. Deliberately absent: any `current_balance_irr`,
which `:469` prohibits without a ledger, and any combined `status` column — see
`app/db/models/trader.py` for why the three status axes stay three columns.

**`trader_users.trader_id`, added `NOT NULL`.** `04_Database_Schema.md:345`
requires it and `12_Security_RBAC_Audit.md:334` lists the owning-trader
relationship among the fields an identity record must support. It could not exist
in M2 because `traders` did not. Every ownership guard in M3 reads it, so it is
added as a real constraint rather than a nullable column with a comment. The
upgrade refuses to run against a non-empty `trader_users`: no registration flow
exists before M3 slice 8 and `12_Security_RBAC_Audit.md:386` forbids seeded
credentials in migrations, so rows here mean something happened that this
revision cannot safely guess at. Failing with a sentence beats failing with a
constraint violation.

**`uq_trader_users_primary_contact` is replaced by `uq_trader_users_one_primary`.**
This is the defect. `04_Database_Schema.md:360-362` specifies the index on
`trader_users(trader_id)`; `20260801_0007:178` built it on `is_primary`, because
the key column did not exist and the flag was the only thing left to key on. The
constraint that shipped therefore enforced **one primary trader contact in the
entire database** instead of one per business, and would have failed on the second
trader ever registered — with a unique violation on a column the caller never set.
Nothing caught it: the drift check compares the migration against the model and
both said `is_primary`, and the constraint test asserted a duplicate is rejected,
which a global singleton does with enthusiasm.

**A value CHECK on `admin_users.status` and `trader_users.status`.** DOC-CONFLICT-037
was Open and its interim rule said in terms that these two columns ship with no
value CHECK, "added by expand/contract once the lifecycle is approved". It is now
Resolved: four values, with `locked`, `pending` and `inactive` refused for the
reasons recorded on `ACCOUNT_STATUSES` and in the conflict row. The predicate of
the new partial index depends on that decision — it reads `status <> 'deactivated'`
where the old one read `status <> 'inactive'`, and had the CHECK landed without the
index changing, the predicate would have named a value the CHECK forbids and the
index would have quietly degenerated to `is_primary = TRUE`.

This is the first `op.create_check_constraint` in the tree; every earlier CHECK is
inline in `op.create_table`, which is not available for a table that already
exists. The name is wrapped in `op.f()` so the `ck` naming convention is not
applied twice.

`traders` receives `GRANT UPDATE` and not `DELETE`: approval, suspension and
`record_version` are updates, and a trader business is never deleted.

Downgrade reverses all four changes in order. Honest only while `traders` and
`trader_users` are empty, on the same terms `20260801_0012:44-46` records — and
note that it restores `uq_trader_users_primary_contact`, which means restoring the
defect. That is what reverting this revision means.

Revision ID: 20260808_0013
Revises: 20260801_0012
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260808_0013"
down_revision: str | Sequence[str] | None = "20260801_0012"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Approved by DOC-CONFLICT-037 (Resolved 2026-08-08) and recorded in
# `status_catalog.yaml`. Kept as SQL text here and as a tuple in
# `app/db/models/identity.py`; `tests/backend/test_status_catalogue_drift.py`
# compares the model's set against the catalogue, and
# `tests/integration/test_schema_matches_models.py` compares model to database.
ACCOUNT_STATUSES_SQL = "'active', 'suspended', 'recovery_required', 'deactivated'"

# Mutable, so the runtime needs more than the fail-closed SELECT+INSERT default
# that `infra/postgres/bootstrap/020-runtime-roles.sql:95-96` grants. UPDATE only:
# approval and suspension are updates and nothing deletes a trader business.
UPDATE_ONLY_TABLES: tuple[str, ...] = ("traders",)


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE": settings.app_db_role,
        "WORKER_DB_ROLE": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(str(value) for value in configured.values())


def _require_empty(table: str) -> None:
    """Refuse to proceed rather than guess at rows this revision cannot repair."""

    bind = op.get_bind()
    count = bind.execute(sa.text(f'SELECT count(*) FROM public."{table}"')).scalar_one()
    if count:
        raise RuntimeError(
            f"Migration {revision} adds a NOT NULL owning-trader column to "
            f'public."{table}", which holds {count} row(s). No registration flow '
            "exists before M3 slice 8 and 12_Security_RBAC_Audit.md:386 forbids "
            "seeded credentials in migrations, so these rows have no safe default "
            "owner. Backfill trader_id deliberately, then re-run."
        )


def upgrade() -> None:
    op.create_table(
        "traders",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=True),
        sa.Column("primary_phone", sa.String(length=32), nullable=False),
        sa.Column("operational_status", sa.String(length=24), nullable=False),
        sa.Column("approval_status", sa.String(length=24), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approved_by_admin_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("risk_level", sa.String(length=24), nullable=True),
        sa.Column("credit_limit_irr", sa.BigInteger(), nullable=True),
        sa.Column("notes_internal", sa.Text(), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "credit_limit_irr IS NULL OR credit_limit_irr >= 0",
            name=op.f("ck_traders_credit_limit_irr_not_negative"),
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0",
            name=op.f("ck_traders_display_name_not_blank"),
        ),
        sa.CheckConstraint(
            "length(btrim(primary_phone)) > 0",
            name=op.f("ck_traders_primary_phone_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_traders_approved_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_traders")),
        sa.UniqueConstraint("primary_phone", name=op.f("uq_traders_primary_phone")),
    )
    op.create_index(
        "idx_traders_status_approval",
        "traders",
        ["operational_status", "approval_status"],
        unique=False,
    )

    _require_empty("trader_users")
    op.add_column(
        "trader_users",
        sa.Column("trader_id", postgresql.UUID(as_uuid=True), nullable=False),
    )
    op.create_foreign_key(
        op.f("fk_trader_users_trader_id_traders"),
        "trader_users",
        "traders",
        ["trader_id"],
        ["id"],
    )

    # The defect and its fix. The predicate changes with the index because the
    # value `inactive` is not an account status under DOC-CONFLICT-037; leaving it
    # would name a value the CHECK below forbids, and the partial index would then
    # match every primary row rather than the live ones.
    op.drop_index(
        "uq_trader_users_primary_contact",
        table_name="trader_users",
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'inactive'"),
    )
    op.create_index(
        "uq_trader_users_one_primary",
        "trader_users",
        ["trader_id"],
        unique=True,
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'deactivated'"),
    )

    for table in ("admin_users", "trader_users"):
        op.create_check_constraint(
            op.f(f"ck_{table}_status"),
            table,
            f"status IN ({ACCOUNT_STATUSES_SQL})",
        )

    bind = op.get_bind()
    for role in _runtime_roles():
        for table in UPDATE_ONLY_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE ON public."{table}" TO "{role}"'))

    # No INSERT of any kind. 12_Security_RBAC_Audit.md:386 forbids seeded
    # credentials, and a seeded trader would be a real counterparty nobody approved.


def downgrade() -> None:
    for table in ("trader_users", "admin_users"):
        op.drop_constraint(op.f(f"ck_{table}_status"), table, type_="check")

    op.drop_index(
        "uq_trader_users_one_primary",
        table_name="trader_users",
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'deactivated'"),
    )
    # Restores the system-wide singleton. Reverting this revision reinstates the
    # defect it exists to fix; that is what a downgrade of a correction means.
    op.create_index(
        "uq_trader_users_primary_contact",
        "trader_users",
        ["is_primary"],
        unique=True,
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'inactive'"),
    )

    op.drop_constraint(
        op.f("fk_trader_users_trader_id_traders"), "trader_users", type_="foreignkey"
    )
    op.drop_column("trader_users", "trader_id")

    op.drop_index("idx_traders_status_approval", table_name="traders")
    op.drop_table("traders")
