"""Create the identity and RBAC schema. No authentication behaviour.

Two identity tables rather than one with a type flag, because M3 must prove an
admin session is rejected on a trader surface and the reverse — with one table
that test is unfalsifiable, and the only separation is a WHERE clause somebody
can forget.

Generated by `alembic revision --autogenerate` against a database already at
20260801_0006, then edited only to add the grants. Hand-transcribing twelve
tables' worth of columns is how a type or a default drifts from its model;
`tests/integration/test_schema_matches_models.py` would catch it, and generating
means there is nothing to catch.

The grants at the end are required by the fail-closed default from
20260801_0005: a table nobody grants on is immutable. Every table here is
mutable — an admin's failed-login counter, a role's description, a revocation
timestamp — so each needs the explicit grant. `auth_events`, which is
append-only, arrives in a later revision and deliberately gets none.

Downgrade drops what it created. These tables hold no recorded evidence yet:
the append-only security-event store is separate and is not dropped by anything.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260801_0007"
down_revision: str | Sequence[str] | None = "20260801_0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("username", postgresql.CITEXT(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("phone_number", sa.String(length=32), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column(
            "security_stamp_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "failed_login_count >= 0", name=op.f("ck_admin_users_failed_login_count_not_negative")
        ),
        sa.CheckConstraint(
            "length(btrim(username::text)) > 0", name=op.f("ck_admin_users_username_not_blank")
        ),
        sa.CheckConstraint(
            "security_stamp_version > 0",
            name=op.f("ck_admin_users_security_stamp_version_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_users")),
        sa.UniqueConstraint("username", name=op.f("uq_admin_users_username")),
    )
    op.create_index(
        "uq_admin_users_email",
        "admin_users",
        ["email"],
        unique=True,
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.create_index(
        "uq_admin_users_phone_number",
        "admin_users",
        ["phone_number"],
        unique=True,
        postgresql_where=sa.text("phone_number IS NOT NULL"),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("domain", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code LIKE '%%.%%'", name=op.f("ck_permissions_code_is_dotted")),
        sa.CheckConstraint("code = lower(code)", name=op.f("ck_permissions_code_is_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("code", name=op.f("uq_permissions_code")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name=op.f("ck_roles_code_is_lowercase")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "trader_users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("phone_number", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("password_changed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "security_stamp_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False
        ),
        sa.Column("failed_login_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "failed_login_count >= 0", name=op.f("ck_trader_users_failed_login_count_not_negative")
        ),
        sa.CheckConstraint(
            "length(btrim(phone_number)) > 0", name=op.f("ck_trader_users_phone_number_not_blank")
        ),
        sa.CheckConstraint(
            "security_stamp_version > 0",
            name=op.f("ck_trader_users_security_stamp_version_positive"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trader_users")),
        sa.UniqueConstraint("phone_number", name=op.f("uq_trader_users_phone_number")),
    )
    op.create_index(
        "uq_trader_users_primary_contact",
        "trader_users",
        ["is_primary"],
        unique=True,
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'inactive'"),
    )
    op.create_table(
        "admin_user_roles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("admin_user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_by_admin_id", sa.UUID(), nullable=True),
        sa.Column("revocation_reason", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(revoked_at IS NULL AND revoked_by_admin_id IS NULL) OR (revoked_at IS NOT NULL)",
            name=op.f("ck_admin_user_roles_revocation_fields_move_together"),
        ),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_user_roles_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_user_roles_granted_by_admin_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["revoked_by_admin_id"],
            ["admin_users.id"],
            name=op.f("fk_admin_user_roles_revoked_by_admin_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_admin_user_roles_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_user_roles")),
    )
    op.create_index(
        "idx_admin_user_roles_admin", "admin_user_roles", ["admin_user_id"], unique=False
    )
    op.create_index(
        "uq_admin_user_roles_live_grant",
        "admin_user_roles",
        ["admin_user_id", "role_id"],
        unique=True,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    # ### end Alembic commands ###

    _grant_mutation()


# Every table this revision creates is mutable. Since 20260801_0005 the
# provisioning default grants only SELECT and INSERT, so without this the runtime
# could create an admin but never update their failed-login count or revoke a
# role — and the failure would appear as a permission error in a request rather
# than at deploy time.
MUTABLE_TABLES = (
    "admin_users",
    "trader_users",
    "permissions",
    "roles",
    "role_permissions",
    "admin_user_roles",
)


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE (or APP_DB_USER)": settings.app_db_role,
        "WORKER_DB_ROLE (or WORKER_DB_USER)": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(value for value in configured.values() if value)


def _grant_mutation() -> None:
    bind = op.get_bind()
    for role in _runtime_roles():
        for table in MUTABLE_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE, DELETE ON public."{table}" TO "{role}"'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("role_permissions")
    op.drop_index(
        "uq_admin_user_roles_live_grant",
        table_name="admin_user_roles",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_index("idx_admin_user_roles_admin", table_name="admin_user_roles")
    op.drop_table("admin_user_roles")
    op.drop_index(
        "uq_trader_users_primary_contact",
        table_name="trader_users",
        postgresql_where=sa.text("is_primary = TRUE AND status <> 'inactive'"),
    )
    op.drop_table("trader_users")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index(
        "uq_admin_users_phone_number",
        table_name="admin_users",
        postgresql_where=sa.text("phone_number IS NOT NULL"),
    )
    op.drop_index(
        "uq_admin_users_email",
        table_name="admin_users",
        postgresql_where=sa.text("email IS NOT NULL"),
    )
    op.drop_table("admin_users")
    # ### end Alembic commands ###
