"""Add the bank profile, version, account and mapping foundation.

Generated by `alembic revision --autogenerate` against a database at 20260801_0011,
then edited in three ways: to break the table-creation cycle, to add the grants, and
to fix the downgrade.

**Autogenerate produced a migration that could not be applied.** `bank_profiles` and
`bank_profile_versions` reference each other, and Alembic emitted both foreign keys
inline while ordering versions first — so the first `CREATE TABLE` referenced a
`bank_profiles` that did not exist yet. Verified by applying it: `relation
"bank_profiles" does not exist`. The fix is the ordinary one for a cycle: create
`bank_profiles` **without** the pointer, create `bank_profile_versions`, then add the
composite deferrable foreign key with `op.create_foreign_key`. Recorded here because
the next model with a circular reference will hit the same thing, and the symptom
appears at deploy time rather than at autogenerate time.

**The pointer constraint is composite, ordered and deferred**, matching what slice 3
proved: `(current_version_id, id) REFERENCES bank_profile_versions (id,
bank_profile_id)`. The invariant is "the current version belongs to **this**
profile", which the single-column form does not express, and the column order is
load-bearing — reversed it still validates and means something else.
`DEFERRABLE INITIALLY DEFERRED` is what lets a profile and its first version be
inserted in one transaction instead of leaving a window where the pointer is null.

**Two tables receive a column-level UPDATE grant, which is new in this schema.**
`bank_profile_versions` and `bank_mappings` are immutable configuration snapshots:
superseded by inserting a new row, never edited. But their `status` must still move
under a controlled transition. `GRANT UPDATE (status)` says exactly that, and
nothing weaker does — a table-level `GRANT UPDATE` would also permit rewriting a
transfer limit or a mapping under an already-approved batch, and "we only update
status" as a convention is not a constraint.

`bank_profiles` and `bank_accounts` are ordinary mutable current-state tables and get
table-level UPDATE. No table in this revision receives DELETE, for the same reason as
20260801_0011: a bank configuration a batch was built against is evidence of how that
batch was built.

**Nothing is seeded.** Not a profile, not a limit, not a cutoff time, not a mapping.
ADR-007's safe default is synthetic fixtures only, and a seeded transfer limit would
silently drive real splitting the first time a batch was built. The fixtures live in
`tests/fixtures/bank_fixtures.py` where only tests can reach them, and an integration
test asserts this revision inserts no rows at all.

Downgrade drops the four tables after detaching the pointer, in the reverse order.
Honest only while they are empty: a bank profile version is the configuration a batch
was built against, so this shares the limit stated in 20260801_0004.

Revision ID: 20260801_0012
Revises: 20260801_0011
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "20260801_0012"
down_revision: str | Sequence[str] | None = "20260801_0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Ordinary current-state tables: a profile is renamed, an account is deactivated.
UPDATE_ONLY_TABLES: tuple[str, ...] = ("bank_profiles", "bank_accounts")

# Immutable snapshots whose status alone may move. The column list is the grant.
STATUS_ONLY_UPDATE_TABLES: tuple[str, ...] = ("bank_profile_versions", "bank_mappings")

POINTER_CONSTRAINT = "fk_bank_profiles_current_version_within_profile"


def _runtime_roles() -> tuple[str, ...]:
    from app.core.config import load_settings

    settings = load_settings()
    configured = {
        "APP_DB_ROLE (or APP_DB_USER)": settings.app_db_role,
        "WORKER_DB_ROLE (or WORKER_DB_USER)": settings.worker_db_role,
    }
    missing = sorted(name for name, value in configured.items() if not value)
    if missing:
        raise RuntimeError(
            f"Migration {revision} grants on mutable tables and these roles are "
            f"not set: {', '.join(missing)}."
        )
    return tuple(value for value in configured.values() if value)


def upgrade() -> None:
    # `bank_profiles` first and without the pointer, so the cycle has a starting
    # point. The constraint is attached after both tables exist.
    op.create_table(
        "bank_profiles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current_version_id", sa.UUID(), nullable=True),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code = lower(code)", name=op.f("ck_bank_profiles_code_is_lowercase")),
        sa.CheckConstraint("length(btrim(code)) > 0", name=op.f("ck_bank_profiles_code_not_blank")),
        sa.CheckConstraint("length(btrim(name)) > 0", name=op.f("ck_bank_profiles_name_not_blank")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_profiles")),
        sa.UniqueConstraint("code", name=op.f("uq_bank_profiles_code")),
    )
    op.create_table(
        "bank_profile_versions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("bank_profile_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("default_transfer_limit_irr", sa.BigInteger(), nullable=True),
        sa.Column("after_cutoff_transfer_limit_irr", sa.BigInteger(), nullable=True),
        sa.Column("cutoff_time", sa.Time(), nullable=True),
        sa.Column(
            "splitting_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "supports_description_field",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
        sa.Column(
            "required_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "config_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_bank_profile_versions_config_hash_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "after_cutoff_transfer_limit_irr IS NULL OR after_cutoff_transfer_limit_irr > 0",
            name=op.f("ck_bank_profile_versions_after_cutoff_limit_positive_when_set"),
        ),
        sa.CheckConstraint(
            "default_transfer_limit_irr IS NULL OR default_transfer_limit_irr > 0",
            name=op.f("ck_bank_profile_versions_default_limit_positive_when_set"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from",
            name=op.f("ck_bank_profile_versions_effective_window_is_ordered"),
        ),
        sa.CheckConstraint(
            "version_number > 0", name=op.f("ck_bank_profile_versions_version_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["bank_profile_id"],
            ["bank_profiles.id"],
            name=op.f("fk_bank_profile_versions_bank_profile_id_bank_profiles"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_bank_profile_versions_created_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_profile_versions")),
        sa.UniqueConstraint(
            "bank_profile_id", "config_hash", name="uq_bank_profile_versions_config_hash"
        ),
        sa.UniqueConstraint(
            "bank_profile_id", "version_number", name="uq_bank_profile_versions_number"
        ),
        # Looks redundant against the primary key and is not: PostgreSQL requires a
        # unique over exactly the column list a composite foreign key references.
        sa.UniqueConstraint("id", "bank_profile_id", name="uq_bank_profile_versions_id_profile"),
    )
    op.create_index(
        "idx_bank_profile_versions_profile",
        "bank_profile_versions",
        ["bank_profile_id", "version_number"],
        unique=False,
    )
    # The cycle closes here, deferred, so both rows can be written in one
    # transaction and the check happens at commit.
    op.create_foreign_key(
        POINTER_CONSTRAINT,
        "bank_profiles",
        "bank_profile_versions",
        ["current_version_id", "id"],
        ["id", "bank_profile_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_table(
        "bank_accounts",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("bank_profile_id", sa.UUID(), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("account_number", sa.String(length=64), nullable=True),
        sa.Column("deposit_number", sa.String(length=64), nullable=True),
        sa.Column("iban", sa.String(length=64), nullable=True),
        sa.Column("normalized_iban", sa.String(length=26), nullable=True),
        sa.Column("account_role", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("record_version", sa.BigInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_role IN ('outgoing_source', 'incoming_destination', 'both')",
            name=op.f("ck_bank_accounts_account_role"),
        ),
        sa.CheckConstraint(
            "length(btrim(display_name)) > 0", name=op.f("ck_bank_accounts_display_name_not_blank")
        ),
        # Null-tolerant on purpose: a centre account may be registered before its
        # IBAN is known, and the beneficiaries' NOT NULL form would refuse it.
        sa.CheckConstraint(
            "normalized_iban IS NULL OR normalized_iban ~ '^IR[0-9]{24}$'",
            name=op.f("ck_bank_accounts_normalized_iban_shape"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_profile_id"],
            ["bank_profiles.id"],
            name=op.f("fk_bank_accounts_bank_profile_id_bank_profiles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_accounts")),
        sa.UniqueConstraint("normalized_iban", name=op.f("uq_bank_accounts_normalized_iban")),
    )
    op.create_index(
        "idx_bank_accounts_profile_role",
        "bank_accounts",
        ["bank_profile_id", "account_role"],
        unique=False,
    )
    op.create_table(
        "bank_mappings",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("bank_profile_version_id", sa.UUID(), nullable=False),
        sa.Column("file_type", sa.String(length=60), nullable=False),
        sa.Column("template_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "required_fields",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "normalization_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("sample_header_hash", sa.String(length=64), nullable=True),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column("approved_by_admin_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "config_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_bank_mappings_config_hash_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "sample_header_hash IS NULL OR sample_header_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_bank_mappings_sample_header_hash_is_lowercase_hex"),
        ),
        sa.CheckConstraint(
            "length(btrim(file_type)) > 0", name=op.f("ck_bank_mappings_file_type_not_blank")
        ),
        sa.CheckConstraint(
            "template_version > 0", name=op.f("ck_bank_mappings_template_version_positive")
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_bank_mappings_approved_by_admin_user_id_admin_users"),
        ),
        sa.ForeignKeyConstraint(
            ["bank_profile_version_id"],
            ["bank_profile_versions.id"],
            name=op.f("fk_bank_mappings_bank_profile_version_id_bank_profile_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by_admin_user_id"],
            ["admin_users.id"],
            name=op.f("fk_bank_mappings_created_by_admin_user_id_admin_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bank_mappings")),
        # Both scoped by file_type, so an import mapping and an export mapping can
        # each be template_version 1 for the same bank version.
        sa.UniqueConstraint(
            "bank_profile_version_id",
            "file_type",
            "config_hash",
            name="uq_bank_mappings_config_hash",
        ),
        sa.UniqueConstraint(
            "bank_profile_version_id",
            "file_type",
            "template_version",
            name="uq_bank_mappings_template_version",
        ),
    )
    op.create_index(
        "idx_bank_mappings_version_type",
        "bank_mappings",
        ["bank_profile_version_id", "file_type"],
        unique=False,
    )

    bind = op.get_bind()
    for role in _runtime_roles():
        for table in UPDATE_ONLY_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE ON public."{table}" TO "{role}"'))
        # Column-level. The immutable snapshot's status may move; nothing else in
        # the row may, and the database is what says so.
        for table in STATUS_ONLY_UPDATE_TABLES:
            bind.execute(sa.text(f'GRANT UPDATE (status) ON public."{table}" TO "{role}"'))

    # No INSERT of any kind. ADR-007 permits synthetic fixtures only, and a seeded
    # transfer limit would drive real splitting decisions.


def downgrade() -> None:
    op.drop_index("idx_bank_mappings_version_type", table_name="bank_mappings")
    op.drop_table("bank_mappings")
    op.drop_index("idx_bank_accounts_profile_role", table_name="bank_accounts")
    op.drop_table("bank_accounts")
    # The pointer goes before the tables it ties together, or the drop order is a
    # cycle again.
    op.drop_constraint(POINTER_CONSTRAINT, "bank_profiles", type_="foreignkey")
    op.drop_index("idx_bank_profile_versions_profile", table_name="bank_profile_versions")
    op.drop_table("bank_profile_versions")
    op.drop_table("bank_profiles")
